# Site settings
#title: Your awesome title
title: Andrey Stolyarov's Blog
email: d10xa@mail.ru
description: Блог о программировании
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://d10xa.github.io" # the base hostname & protocol for your site
twitter_username: d100xa
github_username:  d10xa

# Build settings
markdown: kramdown
