title: Andrey Stolyarov
email: d10xa@mail.ru
description: Блог о программировании
baseurl: ""
url: "http://d10xa.ru"
twitter_username: d100xa
github_username:  d10xa

markdown: kramdown
permalink: /:year/:month/:title