title: Andrey Stolyarov
email: d10xa@mail.ru
description: Блог о программировании
baseurl: ""
url: "https://d10xa.ru"
github_username:  d10xa

markdown: kramdown
permalink: /:year/:month/:title
defaults:
  - scope:
      path: apps
#      type: pages
    values:

      layout: null
      permalink: /:basename/
      categories:
        - app
