@startuml name
start
:Преобразование scala.meta.Tree => SbtTree;
repeat
if (В рамках одной Scope, есть Module с подходящим для него Value?) then (да)
  :подставляем версию модулю (дерево не изменяется);
endif
:вытаскиваем Values на один уровень выше (если Values переместились то дерево изменилось);
:вытаскиваем Modules на один уровень выше (если Modules переместились то дерево изменилось);
repeat while (дерево изменилось?) is (да)
-> нет;
:подставляем версии модулям, которые находятся на разной глубине дерева;
:сворачивание дерева в плоский набор модулей;
stop
@enduml
